[package]
name = "shared"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true

[lib]
doctest = false

[dependencies]
lazy_static = "1.3"
regex = "1.1.0"
thiserror = "1.0.37"
bs58 = "0.5.1"
serde = { version = "1.0.97", features = ["derive"] }
serde_json = "1.0.96"
reqwest = "0.12.5"
log = "0.4.17"
